# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black-jupyter
        fail_fast: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-check-ast
      - id: nbqa-isort
        additional_dependencies:
          - isort==5.12.0
      - id: nbqa-pyupgrade
        additional_dependencies:
          - pyupgrade==3.16.0
        args: [--py312-plus]
      - id: nbqa-mypy
        additional_dependencies:
          - mypy==1.11.0
        args: [--allow-untyped-defs, --allow-untyped-call]
      - id: nbqa-flake8
        additional_dependencies:
          - flake8==7.1.0
          - flake8-bugbear==23.9.16
          - flake8-comprehensions==3.14.0
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0  # Sync with nbqa version above
    hooks:
      - id: mypy
        args: [--allow-untyped-defs, --allow-untyped-call]  # Sync with nbqa version above
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2  # Sync with nbqa version above
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0  # Sync with nbqa version above
    hooks:
      - id: pyupgrade
        args: [--py311-plus, --keep-runtime-typing]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.9.16
          - flake8-comprehensions==3.14.0
